### ISSUE TITLE
Support for direct jar uploading to AWS Lambda

### ISSUE THREAD

**Issue by silvaren** [gilt/sbt-aws-lambda#25]
Hi, I had a pull request open about this, but I figured it would be nicer to have an issue open before.

I needed this functionality of direct jar upload to AWS Lambda so that I wouldn't have to upload my jars to S3 before creating/updating my lambda functions, so if you guys are interested in this I can reopen the pull request about it.

**Comment by gheine** [comment]
Sounds like a reasonable request. Thanks for your contribution! Mind re-opening your PR or submitting a new one?

**Comment by silvaren** [comment]
@gheine just did! I'll be glad to change whatever is needed in the code.
