### ISSUE TITLE
Support for Dead Letter Queue Configuration

### ISSUE THREAD

**Issue by ajr2493** [gilt/sbt-aws-lambda#27]
Hi,

As you may know, AWS released support for Dead Letter Queues (see https://docs.aws.amazon.com/lambda/latest/dg/dlq.html)

I may make a PR for this, but it would be a nice feature to have this config option.

**Comment by gheine** [comment]
Yes, this sounds like a useful feature to add. Please send us a PR!

**Comment by ajr2493** [comment]
Hey, here's the PR: https://github.com/gilt/sbt-aws-lambda/pull/28
Please review when you get a chance, thanks!
