### ISSUE TITLE
Example handler implemenatation

### ISSUE THREAD

**Issue by sscarduzio** [gilt/sbt-aws-lambda#41]
Hi thanks for the plugin! 
Where can I find an example? For example, I can't find the information about what the handler function signature should be.

**Comment by gheine** [comment]
Hi, the handler function signature completely depends on who/what is invoking your lambda and with that what the input and output types of the lambda are. See https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-core/src/main/java/com/amazonaws/services/lambda/runtime/RequestHandler.java and https://docs.aws.amazon.com/lambda/latest/dg/java-handler-using-predefined-interfaces.html
