### ISSUE TITLE
Default region should be account default, not US-EAST-1

### ISSUE THREAD

**Issue by fiadliel** [gilt/sbt-aws-lambda#7]
IMHO, US-EAST-1 is a useful default for accounts which were created up to... eh... 2012? So it's great for early adopters :smile: But since more recent accounts may a different default region, the default region in this code should be that same default.

(I file this issue without checking how easy it is to actually do in code).

**Comment by larroy** [comment]
+1 this prevents setting the region as environment variable. It doesn't get picked up

**Comment by gheine** [comment]
https://github.com/gilt/sbt-aws-lambda/pull/3 https://github.com/gilt/sbt-aws-lambda/pull/23 https://github.com/gilt/sbt-aws-lambda/pull/48
